<?php
    // Use this space to change the default page variables.
    // $loggedin = true;
    
    // Leave this in, loads all state and style.
    include("./includes/full_mission_control_header.php");

    // Custom PHP goes here...
?>

<div class="even_gutter row">
  <!--<button type="button" class="btn btn-xs btn-success nvmarg" data-toggle="modal" data-target="#widget_builder_modal" >Widget Builder</button>-->
  <div class="col-md-6 even_gutter">
    <div class="row dashboard_badges even_gutter">
      <div class="col-sm-12 even_gutter">
        <div class="card card-mini vmarg">
          <div class="card-header">
            <div class="card-title"><span class="fa fa-thumb-tack fa-lg"></span>&emsp;Message of the day</div>
          </div>
          <div class="card-body card-body-padding ">
            <h4 id="welcome-to-the-crowdsourcer-io-dashboard">Build your Mission Control Page here!</h4>
            <p>
              This page is here for you to view. <strong><u>Please do not edit this file!!! Make a copy first!</u></strong>. You can use any components on this page, or you can choose to remove them. Also, please follow naming conventions on the <a href="/">front page</a>. If you have any questions, comments or concerns, please contact us at <a href="https://crowdsourcer.io/mission-control/29"/><i class="fa fa-rocket"></i> Mission Control.</a>
            </p>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent fringilla elementum rhoncus. Aliquam turpis dolor, lacinia nec egestas sed, pretium non erat. Curabitur sagittis tortor leo, quis efficitur lorem pulvinar eget. Mauris maximus, ante eget posuere imperdiet, odio enim mollis nulla, eget tempor dolor massa sit amet ligula. Etiam rutrum ligula quam, id mattis ipsum malesuada sed. Nam lobortis, lectus non vulputate ultrices, justo orci faucibus est, interdum malesuada ipsum ipsum nec ipsum. Aliquam interdum, nulla id iaculis molestie, ligula justo vehicula tortor, id maximus est urna sed orci. Suspendisse id dictum velit. Curabitur tincidunt odio a varius rutrum.
            </p>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-12 col-sm-6 vmarg even_gutter">
        <a class="card card-banner card-blue-light" href="/mission-control/29/contributors">
          <div class="card-body">
            <i class="icon fa fa-star-o fa-4x"></i>
            <div class="content">
              <div class="title">Contribution<br>
                <span class="sign">Your points</span>
              </div>
              <div class="value">
                <span id="contribution_pts">0</span><span class="sign">pts</span>
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-6 col-md-12 col-sm-6 vmarg even_gutter">
        <a class="card card-banner card-green-light" href="/mission-control/29/tasks#tab_show_completed">
          <div class="card-body">
            <i class="icon fa fa-thumbs-o-up fa-4x"></i>
            <div class="content">
              <div class="title">Completed<br>
                <span class="sign">By you</span>
              </div>
              <div class="value">
                <span id="tasks_done_user">0</span><span class="sign"> tasks</span>
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-6 col-md-12 col-sm-6 vmarg even_gutter">
        <a class="card card-banner card-orange-light" href="/mission-control/29/tasks">
          <div class="card-body">
            <i class="icon fa fa-tasks fa-4x"></i>
            <div class="content">
              <div class="title">Open tasks<br>
                <span class="sign">Overall</span>
              </div>
              <div class="value"><span id="tasks_todo">
                9</span>
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-6 col-md-12 col-sm-6 vmarg even_gutter">
        <a class="card card-banner card-yellow-light" href="/mission-control/29/tasks">
          <div class="card-body">
            <i class="icon fa fa-clock-o fa-4x"></i>
            <div class="content">
              <div class="title">Begun Tasks<br>
                <span class="sign">Overall</span>
              </div>
              <div class="value"><span class="sign"></span>
                <span id="tasks_doing">7</span>
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-6 col-md-12 col-sm-6 vmarg even_gutter">
        <a class="card card-banner card-green-light" href="/mission-control/29/tasks#tab_show_completed">
          <div class="card-body">
            <i class="icon fa fa-check fa-4x"></i>
            <div class="content">
              <div class="title">Done Tasks<br>
                <span class="sign">Overall</span>
              </div>
              <div class="value"><span class="sign"></span>
                <span id="tasks_done">21</span>
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-6 col-md-12 col-sm-6 vmarg even_gutter">
        <a class="card card-banner card-blue-light" href="/mission-control/29/contributors">
          <div class="card-body">
            <i class="icon fa fa-users fa-4x"></i>
            <div class="content">
              <div class="title">Contributors<br>
                <span class="sign">Overall</span>
              </div>
              <div class="value"><span class="sign"></span>
                14
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
  </div>
  <div class="col-md-6 even_gutter">
    <div class="alert alert-info " role="alert">
      <strong>Need more people in your team?</strong> As Crowdsourcer.io is still in its infancy, we appreciate that there may not be enough applicants to your project. To help you advertise your project, you can use the <a href="" data-toggle="modal" data-target="#widget_builder_modal" class="alert-link">widget builder to generate embeddable code </a>for placement in forums and websites.
    </div>
  </div>
  <div class="col-md-6 even_gutter">
    <div class="card card-mini">
      <div class="card-header">
        <div class="card-title">Your outstanding tasks</div>
        <!--
          <ul class="card-action">
              <li>
                  <a href="#">
                      <i class="fa fa-refresh"></i>
                  </a>
              </li>
          </ul>
          -->
      </div>
      <div class="card-body no_padding table-responsive">
        <table class="table card-table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Details</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr id="task_row185">
              <td>GitHub Repo organisation</td>
              <td>
                <div class="label label-primary">HTML/CSS Developer</div>
                <div class="label label-primary"><span id="task_contr_pts185">2</span>pts</div>
                <span class="label label-warning">Normal</span>
              </td>
              <td>
                <button type="button" class="btn btn-xs btn-danger nvmarg" onclick="abandonTask(185, true)">Abandon</button>
                <button type="button" class="btn btn-xs btn-success nvmarg" data-toggle="modal" data-target="#complete_modal" data-task="185">Complete</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <!--  List  -->
  <div class="col-md-6 even_gutter voffset vmarg position_list">
    <h4 class="vmarg mc_h4">Your positions</h4>
    <div class="list-group nvmarg">
      <a class="list-group-item" href="/mission-control/29/tasks?show=113">
      <span class="badge badge-success badge-icon"><span class="icon_number" aria-hidden="true">0</span><span>Available Tasks</span></span>
      <span class="badge badge-warning badge-icon"><span class="icon_number" aria-hidden="true">0</span><span>In Review</span></span>
      HTML/CSS Developer                </a>
    </div>
  </div>
  <!--  End List  -->
</div>

<? include("./partials/footer.php"); ?>
